# Generated by Django 5.1.15 on 2026-07-11 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Employee ID')),
                ('designation', models.CharField(max_length=255, verbose_name='Designation')),
                ('qualification', models.CharField(max_length=255, verbose_name='Qualification')),
                ('specialization', models.CharField(max_length=255, verbose_name='Specialization')),
                ('experience_years', models.PositiveIntegerField(verbose_name='Experience (Years)')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Address')),
                ('joining_date', models.DateField(verbose_name='Joining Date')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='teacher_profiles/', verbose_name='Profile Photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='departments.department', verbose_name='Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['employee_id'],
                'indexes': [models.Index(fields=['employee_id'], name='teachers_te_employe_8033d0_idx'), models.Index(fields=['department'], name='teachers_te_departm_e41848_idx'), models.Index(fields=['designation'], name='teachers_te_designa_4baf7f_idx'), models.Index(fields=['is_active'], name='teachers_te_is_acti_964ac2_idx')],
            },
        ),
    ]
