# Generated by Django 5.1.15 on 2026-07-11 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('job_title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('internship', 'Internship'), ('contract', 'Contract')], max_length=50, verbose_name='Employment Type')),
                ('package_lpa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Package (LPA)')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('eligibility_criteria', models.TextField(verbose_name='Eligibility Criteria')),
                ('application_deadline', models.DateField(verbose_name='Application Deadline')),
                ('drive_date', models.DateField(verbose_name='Drive Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Placement Drive',
                'verbose_name_plural': 'Placement Drives',
                'ordering': ['-drive_date', 'company_name'],
                'indexes': [models.Index(fields=['company_name'], name='placements__company_847a5f_idx'), models.Index(fields=['drive_date'], name='placements__drive_d_4927d6_idx'), models.Index(fields=['application_deadline'], name='placements__applica_2078ab_idx'), models.Index(fields=['employment_type'], name='placements__employm_e50e58_idx'), models.Index(fields=['is_active'], name='placements__is_acti_0e4b39_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlacementApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='applied', max_length=50, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Applied At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_applications', to='students.student', verbose_name='Student')),
                ('placement_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placements.placementdrive', verbose_name='Placement Drive')),
            ],
            options={
                'verbose_name': 'Placement Application',
                'verbose_name_plural': 'Placement Applications',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['placement_drive'], name='placements__placeme_0e7316_idx'), models.Index(fields=['student'], name='placements__student_d80600_idx'), models.Index(fields=['status'], name='placements__status_971533_idx'), models.Index(fields=['applied_at'], name='placements__applied_1d1ae1_idx')],
                'constraints': [models.UniqueConstraint(fields=('placement_drive', 'student'), name='unique_placement_drive_student')],
            },
        ),
    ]
