# Generated by Django 5.1.15 on 2026-07-11 11:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('funding_agency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Funding Agency')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Budget')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=50, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_projects', to='departments.department', verbose_name='Department')),
                ('principal_investigator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_research_projects', to='teachers.teacher', verbose_name='Principal Investigator')),
            ],
            options={
                'verbose_name': 'Research Project',
                'verbose_name_plural': 'Research Projects',
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ResearchMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('co_investigator', 'Co-Investigator'), ('research_assistant', 'Research Assistant'), ('faculty_member', 'Faculty Member')], max_length=50, verbose_name='Role')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_memberships', to='teachers.teacher', verbose_name='Teacher')),
                ('research_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='research.researchproject', verbose_name='Research Project')),
            ],
            options={
                'verbose_name': 'Research Member',
                'verbose_name_plural': 'Research Members',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['principal_investigator'], name='research_re_princip_25e182_idx'),
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['department'], name='research_re_departm_7d2372_idx'),
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['status'], name='research_re_status_b7f7d0_idx'),
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['start_date'], name='research_re_start_d_7f25da_idx'),
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['is_active'], name='research_re_is_acti_fd570d_idx'),
        ),
        migrations.AddIndex(
            model_name='researchmember',
            index=models.Index(fields=['research_project'], name='research_re_researc_5812c0_idx'),
        ),
        migrations.AddIndex(
            model_name='researchmember',
            index=models.Index(fields=['teacher'], name='research_re_teacher_c3d6c9_idx'),
        ),
        migrations.AddIndex(
            model_name='researchmember',
            index=models.Index(fields=['role'], name='research_re_role_07730a_idx'),
        ),
        migrations.AddIndex(
            model_name='researchmember',
            index=models.Index(fields=['joined_at'], name='research_re_joined__80398f_idx'),
        ),
        migrations.AddConstraint(
            model_name='researchmember',
            constraint=models.UniqueConstraint(fields=('research_project', 'teacher'), name='unique_research_project_teacher'),
        ),
    ]
