# Generated by Django 5.1.15 on 2026-07-11 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('general', 'General'), ('academic', 'Academic'), ('exam', 'Exam'), ('event', 'Event'), ('placement', 'Placement'), ('scholarship', 'Scholarship'), ('finance', 'Finance')], max_length=50, verbose_name='Notification Type')),
                ('target_audience', models.CharField(choices=[('all', 'All'), ('students', 'Students'), ('teachers', 'Teachers'), ('staff', 'Staff'), ('hods', 'HODs')], max_length=50, verbose_name='Target Audience')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('published_at', models.DateTimeField(verbose_name='Published At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-published_at', 'notification_type', 'title'],
                'indexes': [models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['target_audience'], name='notificatio_target__da093b_idx'), models.Index(fields=['created_by'], name='notificatio_created_274d42_idx'), models.Index(fields=['published_at'], name='notificatio_publish_71787c_idx'), models.Index(fields=['expires_at'], name='notificatio_expires_4f3289_idx'), models.Index(fields=['is_active'], name='notificatio_is_acti_7de9ed_idx')],
            },
        ),
    ]
