# Generated by Django 5.1.15 on 2026-07-11 09:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Employee ID')),
                ('designation', models.CharField(max_length=255, verbose_name='Designation')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Address')),
                ('joining_date', models.DateField(verbose_name='Joining Date')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='staff_profiles/', verbose_name='Profile Photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='departments.department', verbose_name='Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ['employee_id'],
                'indexes': [models.Index(fields=['employee_id'], name='staff_staff_employe_f8cd0b_idx'), models.Index(fields=['department'], name='staff_staff_departm_5ebced_idx'), models.Index(fields=['designation'], name='staff_staff_designa_1ae0e9_idx'), models.Index(fields=['is_active'], name='staff_staff_is_acti_0db61a_idx')],
            },
        ),
    ]
