# Generated by Django 5.1.15 on 2026-07-11 11:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('event_type', models.CharField(choices=[('seminar', 'Seminar'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('cultural', 'Cultural'), ('sports', 'Sports'), ('placement', 'Placement'), ('other', 'Other')], max_length=50, verbose_name='Event Type')),
                ('venue', models.CharField(max_length=255, verbose_name='Venue')),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('organizer', models.CharField(max_length=255, verbose_name='Organizer')),
                ('registration_required', models.BooleanField(default=True, verbose_name='Registration Required')),
                ('registration_deadline', models.DateField(blank=True, null=True, verbose_name='Registration Deadline')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_date', 'start_time'],
                'indexes': [models.Index(fields=['event_date'], name='events_even_event_d_2c2da5_idx'), models.Index(fields=['event_type'], name='events_even_event_t_a87b5c_idx'), models.Index(fields=['is_active'], name='events_even_is_acti_82811f_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('cancelled', 'Cancelled')], default='registered', max_length=50, verbose_name='Status')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered At')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['event'], name='events_even_event_i_9a7faf_idx'), models.Index(fields=['student'], name='events_even_student_eaf200_idx'), models.Index(fields=['status'], name='events_even_status_bdf692_idx'), models.Index(fields=['registered_at'], name='events_even_registe_659dc9_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'student'), name='unique_event_student')],
            },
        ),
    ]
