# Generated by Django 5.1.15 on 2026-07-11 10:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('departments', '0001_initial'),
        ('semester', '0002_semester_name'),
        ('subjects', '0002_remove_subject_subjects_su_departm_1115a0_idx_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=50, verbose_name='Day of Week')),
                ('period_number', models.PositiveIntegerField(verbose_name='Period Number')),
                ('room_number', models.CharField(max_length=50, verbose_name='Room Number')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='courses.course', verbose_name='Course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='departments.department', verbose_name='Department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='semester.semester', verbose_name='Semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='subjects.subject', verbose_name='Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='teachers.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
                'ordering': ['day_of_week', 'period_number', 'start_time'],
                'indexes': [models.Index(fields=['department'], name='timetable_t_departm_bb4145_idx'), models.Index(fields=['course'], name='timetable_t_course__ab74fd_idx'), models.Index(fields=['semester'], name='timetable_t_semeste_5e8d5d_idx'), models.Index(fields=['subject'], name='timetable_t_subject_aed3e2_idx'), models.Index(fields=['teacher'], name='timetable_t_teacher_f86295_idx'), models.Index(fields=['day_of_week'], name='timetable_t_day_of__2718e7_idx'), models.Index(fields=['period_number'], name='timetable_t_period__5a74be_idx'), models.Index(fields=['room_number'], name='timetable_t_room_nu_82a814_idx'), models.Index(fields=['start_time'], name='timetable_t_start_t_5be68e_idx'), models.Index(fields=['is_active'], name='timetable_t_is_acti_23fc2b_idx')],
            },
        ),
    ]
