# Generated by Django 5.1.15 on 2026-07-12 08:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('page_type', models.CharField(choices=[('about', 'About'), ('vision', 'Vision'), ('mission', 'Mission'), ('principal_message', 'Principal Message'), ('privacy_policy', 'Privacy Policy'), ('terms', 'Terms'), ('other', 'Other')], max_length=50, verbose_name='Page Type')),
                ('content', models.TextField(verbose_name='Content')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Content Page',
                'verbose_name_plural': 'Content Pages',
                'ordering': ['page_type', 'title'],
                'indexes': [models.Index(fields=['slug'], name='cms_content_slug_e3caa7_idx'), models.Index(fields=['page_type'], name='cms_content_page_ty_6a848b_idx'), models.Index(fields=['is_published'], name='cms_content_is_publ_f3eace_idx')],
            },
        ),
    ]
