# Generated by Django 5.1.15 on 2026-07-11 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semester', '0002_semester_name'),
        ('students', '0001_initial'),
        ('subjects', '0002_remove_subject_subjects_su_departm_1115a0_idx_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('internal_1', 'Internal 1'), ('internal_2', 'Internal 2'), ('model', 'Model'), ('practical', 'Practical'), ('viva', 'Viva'), ('semester', 'Semester')], max_length=50, verbose_name='Exam Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('exam_date', models.DateField(verbose_name='Exam Date')),
                ('maximum_marks', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Maximum Marks')),
                ('passing_marks', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Passing Marks')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instructions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='semester.semester', verbose_name='Semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='subjects.subject', verbose_name='Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='teachers.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Examination',
                'verbose_name_plural': 'Examinations',
                'ordering': ['-exam_date', 'subject', 'exam_type'],
            },
        ),
        migrations.CreateModel(
            name='InternalMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Marks Obtained')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_marks', to='examinations.examination', verbose_name='Examination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_marks', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Internal Mark',
                'verbose_name_plural': 'Internal Marks',
                'ordering': ['examination', 'student'],
            },
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['subject'], name='examination_subject_d7a974_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['semester'], name='examination_semeste_e34439_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['teacher'], name='examination_teacher_a3627b_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['exam_type'], name='examination_exam_ty_b524dc_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['exam_date'], name='examination_exam_da_a689f7_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['is_active'], name='examination_is_acti_f95b00_idx'),
        ),
        migrations.AddIndex(
            model_name='internalmark',
            index=models.Index(fields=['examination'], name='examination_examina_ff97d1_idx'),
        ),
        migrations.AddIndex(
            model_name='internalmark',
            index=models.Index(fields=['student'], name='examination_student_72e6e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='internalmark',
            constraint=models.UniqueConstraint(fields=('examination', 'student'), name='unique_examination_student'),
        ),
    ]
