# Generated by Django 5.1.15 on 2026-07-11 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
        ('semester', '0002_semester_name'),
        ('students', '0001_initial'),
        ('subjects', '0002_remove_subject_subjects_su_departm_1115a0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgpa', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='SGPA')),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='CGPA')),
                ('total_credits_earned', models.PositiveIntegerField(verbose_name='Total Credits Earned')),
                ('result_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('withheld', 'Withheld')], max_length=50, verbose_name='Result Status')),
                ('published_date', models.DateField(verbose_name='Published Date')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semester_results', to='semester.semester', verbose_name='Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_results', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Semester Result',
                'verbose_name_plural': 'Semester Results',
                'ordering': ['-published_date', 'student', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='SemesterResultSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_marks', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Internal Marks')),
                ('external_marks', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='External Marks')),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total Marks')),
                ('grade', models.CharField(max_length=10, verbose_name='Grade')),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Grade Point')),
                ('credits_earned', models.PositiveIntegerField(verbose_name='Credits Earned')),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=50, verbose_name='Result')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('semester_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='examinations.semesterresult', verbose_name='Semester Result')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semester_result_subjects', to='subjects.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Semester Result Subject',
                'verbose_name_plural': 'Semester Result Subjects',
                'ordering': ['semester_result', 'subject'],
            },
        ),
        migrations.AddIndex(
            model_name='semesterresult',
            index=models.Index(fields=['student'], name='examination_student_36cd0b_idx'),
        ),
        migrations.AddIndex(
            model_name='semesterresult',
            index=models.Index(fields=['semester'], name='examination_semeste_29061b_idx'),
        ),
        migrations.AddIndex(
            model_name='semesterresult',
            index=models.Index(fields=['result_status'], name='examination_result__90feb3_idx'),
        ),
        migrations.AddIndex(
            model_name='semesterresult',
            index=models.Index(fields=['published_date'], name='examination_publish_d09b6e_idx'),
        ),
        migrations.AddIndex(
            model_name='semesterresultsubject',
            index=models.Index(fields=['semester_result'], name='examination_semeste_024d49_idx'),
        ),
        migrations.AddIndex(
            model_name='semesterresultsubject',
            index=models.Index(fields=['subject'], name='examination_subject_40a2bd_idx'),
        ),
        migrations.AddIndex(
            model_name='semesterresultsubject',
            index=models.Index(fields=['result'], name='examination_result_15578f_idx'),
        ),
        migrations.AddConstraint(
            model_name='semesterresultsubject',
            constraint=models.UniqueConstraint(fields=('semester_result', 'subject'), name='unique_semester_result_subject'),
        ),
    ]
