# Generated by Django 5.1.15 on 2026-07-11 11:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_year', '0002_academicyear_is_active_and_more'),
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveIntegerField(verbose_name='Semester Number')),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tuition Fee')),
                ('exam_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Exam Fee')),
                ('library_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Library Fee')),
                ('other_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Other Fee')),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Fee')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='academic_year.academicyear', verbose_name='Academic Year')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'ordering': ['course', 'academic_year', 'semester_number'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer')], max_length=50, verbose_name='Payment Method')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=50, verbose_name='Payment Status')),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction Reference')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='students.student', verbose_name='Student')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.feestructure', verbose_name='Fee Structure')),
            ],
            options={
                'verbose_name': 'Fee Payment',
                'verbose_name_plural': 'Fee Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['course'], name='finance_fee_course__c4fb5a_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['academic_year'], name='finance_fee_academi_70a1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['semester_number'], name='finance_fee_semeste_0938ec_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['is_active'], name='finance_fee_is_acti_595955_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['student'], name='finance_fee_student_ce0792_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['fee_structure'], name='finance_fee_fee_str_26eaca_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['payment_status'], name='finance_fee_payment_e45b42_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['payment_date'], name='finance_fee_payment_863cf5_idx'),
        ),
    ]
