# Generated by Django 5.1.15 on 2026-08-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['course', 'academic_year', 'semester_number', 'fee_type'], 'verbose_name': 'Fee Structure', 'verbose_name_plural': 'Fee Structures'},
        ),
        migrations.AddField(
            model_name='feestructure',
            name='fee_type',
            field=models.CharField(choices=[('tuition', 'Semester Tuition Fee'), ('exam', 'Exam Registration Fee'), ('event', 'Event Fee')], default='tuition', help_text='Which of the three ERP fee types this structure represents (Semester Tuition Fee / Exam Registration Fee / Event Fee).', max_length=20, verbose_name='Fee Type'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['fee_type'], name='finance_fee_fee_typ_f5cdd1_idx'),
        ),
    ]
