# Generated by Django 5.1.15 on 2026-07-11 11:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semester', '0002_semester_name'),
        ('subjects', '0002_remove_subject_subjects_su_departm_1115a0_idx_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('material_type', models.CharField(choices=[('notes', 'Notes'), ('pdf', 'PDF'), ('ppt', 'PPT'), ('video', 'Video'), ('link', 'Link'), ('other', 'Other')], max_length=50, verbose_name='Material Type')),
                ('file', models.FileField(blank=True, null=True, upload_to='study_materials/', verbose_name='File')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='External URL')),
                ('uploaded_at', models.DateTimeField(verbose_name='Uploaded At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_materials', to='semester.semester', verbose_name='Semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_materials', to='subjects.subject', verbose_name='Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_materials', to='teachers.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Study Material',
                'verbose_name_plural': 'Study Materials',
                'ordering': ['-uploaded_at', 'subject', 'title'],
                'indexes': [models.Index(fields=['subject'], name='study_mater_subject_eccd6b_idx'), models.Index(fields=['semester'], name='study_mater_semeste_0344a6_idx'), models.Index(fields=['teacher'], name='study_mater_teacher_892eae_idx'), models.Index(fields=['material_type'], name='study_mater_materia_67dc9b_idx'), models.Index(fields=['uploaded_at'], name='study_mater_uploade_d97f44_idx'), models.Index(fields=['is_active'], name='study_mater_is_acti_067cc5_idx')],
            },
        ),
    ]
