# Generated by Django 5.1.15 on 2026-07-11 11:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('stipend', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stipend')),
                ('duration', models.CharField(max_length=100, verbose_name='Duration')),
                ('eligibility', models.TextField(verbose_name='Eligibility')),
                ('application_deadline', models.DateField(verbose_name='Application Deadline')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Internship Opportunity',
                'verbose_name_plural': 'Internship Opportunities',
                'ordering': ['-start_date', 'company_name'],
                'indexes': [models.Index(fields=['company_name'], name='internships_company_83fd42_idx'), models.Index(fields=['start_date'], name='internships_start_d_470055_idx'), models.Index(fields=['application_deadline'], name='internships_applica_598d9a_idx'), models.Index(fields=['is_active'], name='internships_is_acti_82842f_idx')],
            },
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='applied', max_length=50, verbose_name='Status')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Applied At')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_applications', to='students.student', verbose_name='Student')),
                ('internship_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internships.internshipopportunity', verbose_name='Internship Opportunity')),
            ],
            options={
                'verbose_name': 'Internship Application',
                'verbose_name_plural': 'Internship Applications',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['internship_opportunity'], name='internships_interns_e37f74_idx'), models.Index(fields=['student'], name='internships_student_a6faec_idx'), models.Index(fields=['status'], name='internships_status_37245a_idx'), models.Index(fields=['applied_at'], name='internships_applied_eed0ce_idx')],
                'constraints': [models.UniqueConstraint(fields=('internship_opportunity', 'student'), name='unique_internship_opportunity_student')],
            },
        ),
    ]
