# Generated by Django 5.1.15 on 2026-07-11 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('campus', 'Campus'), ('event', 'Event'), ('lab', 'Lab'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('other', 'Other')], max_length=50, verbose_name='Category')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['category'], name='gallery_gal_categor_5b578e_idx'), models.Index(fields=['uploaded_at'], name='gallery_gal_uploade_d79ca6_idx'), models.Index(fields=['is_active'], name='gallery_gal_is_acti_2514ae_idx')],
            },
        ),
    ]
