# Generated by Django 5.1.15 on 2026-07-11 06:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('departments', '0001_initial'),
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Subject Code')),
                ('name', models.CharField(max_length=255, verbose_name='Subject Name')),
                ('credits', models.PositiveIntegerField(verbose_name='Credits')),
                ('subject_type', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('lab', 'Lab'), ('project', 'Project')], max_length=50, verbose_name='Subject Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='courses.course', verbose_name='Course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='departments.department', verbose_name='Department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='semester.semester', verbose_name='Semester')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['course', 'semester', 'code'],
                'indexes': [models.Index(fields=['code'], name='subjects_su_code_22ddd2_idx'), models.Index(fields=['department'], name='subjects_su_departm_1115a0_idx'), models.Index(fields=['course'], name='subjects_su_course__749bf7_idx'), models.Index(fields=['semester'], name='subjects_su_semeste_17f70e_idx'), models.Index(fields=['subject_type'], name='subjects_su_subject_3f1615_idx'), models.Index(fields=['is_active'], name='subjects_su_is_acti_51f8be_idx')],
            },
        ),
    ]
