# Generated by Django 5.1.15 on 2026-07-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subject',
            name='subjects_su_departm_1115a0_idx',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab')], max_length=50, verbose_name='Subject Type'),
        ),
    ]
