# Generated by Django 5.1.15 on 2026-07-11 06:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Course Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Course Code')),
                ('degree', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], max_length=50, verbose_name='Degree Type')),
                ('duration_years', models.PositiveIntegerField(verbose_name='Duration (Years)')),
                ('total_semesters', models.PositiveIntegerField(verbose_name='Total Semesters')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='departments.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['department', 'name'],
                'indexes': [models.Index(fields=['code'], name='courses_cou_code_612388_idx'), models.Index(fields=['department'], name='courses_cou_departm_93b58f_idx'), models.Index(fields=['degree'], name='courses_cou_degree_873b06_idx'), models.Index(fields=['is_active'], name='courses_cou_is_acti_3c7e41_idx'), models.Index(fields=['name'], name='courses_cou_name_eb4cc3_idx')],
            },
        ),
    ]
