# Generated by Django 5.1.15 on 2026-07-11 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('departments', '0001_initial'),
        ('semester', '0002_semester_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=50, unique=True, verbose_name='Admission Number')),
                ('roll_number', models.CharField(max_length=50, verbose_name='Roll Number')),
                ('registration_number', models.CharField(max_length=50, verbose_name='Registration Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=50, verbose_name='Gender')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('guardian_name', models.CharField(max_length=255, verbose_name='Guardian Name')),
                ('guardian_phone', models.CharField(max_length=20, verbose_name='Guardian Phone')),
                ('address', models.TextField(verbose_name='Address')),
                ('admission_date', models.DateField(verbose_name='Admission Date')),
                ('current_semester', models.PositiveIntegerField(verbose_name='Current Semester')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='student_profiles/', verbose_name='Profile Photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='courses.course', verbose_name='Course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='departments.department', verbose_name='Department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='semester.semester', verbose_name='Semester')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['admission_number'],
                'indexes': [models.Index(fields=['admission_number'], name='students_st_admissi_321db4_idx'), models.Index(fields=['roll_number'], name='students_st_roll_nu_6ff92b_idx'), models.Index(fields=['department'], name='students_st_departm_4f05c7_idx'), models.Index(fields=['course'], name='students_st_course__5eee3a_idx'), models.Index(fields=['semester'], name='students_st_semeste_f1648c_idx'), models.Index(fields=['is_active'], name='students_st_is_acti_c00e81_idx')],
            },
        ),
    ]
