# Generated by Django 5.1.15 on 2026-07-11 09:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_phone', models.CharField(max_length=20, verbose_name='Office Phone')),
                ('office_location', models.CharField(max_length=255, verbose_name='Office Location')),
                ('appointment_date', models.DateField(verbose_name='Appointment Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hods', to='departments.department', verbose_name='Department')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hod_details', to='teachers.teacher', verbose_name='Teacher')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hod_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Head of Department',
                'verbose_name_plural': 'Heads of Department',
                'ordering': ['department'],
                'indexes': [models.Index(fields=['department'], name='hod_hod_departm_a909fc_idx'), models.Index(fields=['is_active'], name='hod_hod_is_acti_753ad1_idx')],
            },
        ),
    ]
