# Generated by Django 5.1.15 on 2026-07-11 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_year', '0002_academicyear_is_active_and_more'),
        ('courses', '0001_initial'),
        ('departments', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=50, unique=True, verbose_name='Application Number')),
                ('admission_date', models.DateField(verbose_name='Admission Date')),
                ('admission_type', models.CharField(choices=[('regular', 'Regular'), ('lateral', 'Lateral'), ('management', 'Management')], max_length=50, verbose_name='Admission Type')),
                ('admission_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=50, verbose_name='Admission Status')),
                ('previous_school', models.CharField(max_length=255, verbose_name='Previous School')),
                ('previous_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Previous Percentage')),
                ('entrance_exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Entrance Exam Score')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='academic_year.academicyear', verbose_name='Academic Year')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='courses.course', verbose_name='Course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='departments.department', verbose_name='Department')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
                'ordering': ['application_number'],
                'indexes': [models.Index(fields=['application_number'], name='admissions__applica_6fb346_idx'), models.Index(fields=['department'], name='admissions__departm_29776a_idx'), models.Index(fields=['course'], name='admissions__course__a100ef_idx'), models.Index(fields=['academic_year'], name='admissions__academi_440a84_idx'), models.Index(fields=['admission_type'], name='admissions__admissi_4035b4_idx'), models.Index(fields=['admission_status'], name='admissions__admissi_0d4ed6_idx')],
            },
        ),
    ]
