# Generated by Django 5.1.15 on 2026-07-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_year', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['is_active'], name='academic_ye_is_acti_c6e823_idx'),
        ),
    ]
