# Generated by Django 5.1.15 on 2026-08-14 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0002_remove_subject_subjects_su_departm_1115a0_idx_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Topic')),
                ('question_text', models.TextField(verbose_name='Question')),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('Short Answer', 'Short Answer'), ('Descriptive', 'Descriptive')], max_length=20, verbose_name='Question Type')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Options')),
                ('correct_answer', models.TextField(verbose_name='Correct Answer')),
                ('marks', models.PositiveIntegerField(verbose_name='Marks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_bank_questions', to='subjects.subject', verbose_name='Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_bank_questions', to='teachers.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject'], name='question_ba_subject_1f6e2a_idx'), models.Index(fields=['teacher'], name='question_ba_teacher_6a5d3b_idx'), models.Index(fields=['question_type'], name='question_ba_questio_3c8b1e_idx'), models.Index(fields=['created_at'], name='question_ba_created_9d4f7c_idx')],
            },
        ),
    ]
