# Generated by Django 5.1.15 on 2026-07-11 11:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('scholarship_type', models.CharField(choices=[('merit', 'Merit'), ('need_based', 'Need Based'), ('sports', 'Sports'), ('government', 'Government'), ('private', 'Private')], max_length=50, verbose_name='Scholarship Type')),
                ('provider', models.CharField(max_length=255, verbose_name='Provider')),
                ('description', models.TextField(verbose_name='Description')),
                ('eligibility_criteria', models.TextField(verbose_name='Eligibility Criteria')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('application_deadline', models.DateField(verbose_name='Application Deadline')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
                'ordering': ['-application_deadline', 'name'],
                'indexes': [models.Index(fields=['name'], name='scholarship_name_2a9132_idx'), models.Index(fields=['scholarship_type'], name='scholarship_scholar_f15acd_idx'), models.Index(fields=['provider'], name='scholarship_provide_985952_idx'), models.Index(fields=['application_deadline'], name='scholarship_applica_a56ce8_idx'), models.Index(fields=['is_active'], name='scholarship_is_acti_62e7cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='applied', max_length=50, verbose_name='Status')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Applied At')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarships.scholarship', verbose_name='Scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Scholarship Application',
                'verbose_name_plural': 'Scholarship Applications',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['scholarship'], name='scholarship_scholar_a4fab8_idx'), models.Index(fields=['student'], name='scholarship_student_b2b4a5_idx'), models.Index(fields=['status'], name='scholarship_status_9b5caa_idx'), models.Index(fields=['applied_at'], name='scholarship_applied_66ed3a_idx')],
                'constraints': [models.UniqueConstraint(fields=('scholarship', 'student'), name='unique_scholarship_student')],
            },
        ),
    ]
