# Generated by Django 5.1.15 on 2026-07-11 06:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_year', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveIntegerField(verbose_name='Semester Number')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='academic_year.academicyear', verbose_name='Academic Year')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['academic_year', 'course', 'semester_number'],
                'indexes': [models.Index(fields=['course'], name='semester_se_course__fe7747_idx'), models.Index(fields=['academic_year'], name='semester_se_academi_af1e41_idx'), models.Index(fields=['semester_number'], name='semester_se_semeste_a45993_idx'), models.Index(fields=['is_active'], name='semester_se_is_acti_c52ebd_idx')],
            },
        ),
    ]
